### PR TITLE
Enable GitHub CI on the repo

### PR DESCRIPTION
**Pull request by RadxaYuntian**
* Add one click release workflow on GitHub. [Example](https://github.com/RadxaYuntian/debos-radxa/actions/workflows/build.yml), [result](https://github.com/RadxaYuntian/debos-radxa/actions/runs/1577618307), and the [generated release](https://github.com/RadxaYuntian/debos-radxa/releases/tag/20211214-1310).
> Currently the release title is the build time, and the release note defaults to the most current commit's message. This can be changed.
* Switch to upstream `godebos/debos` docker image.
* Remove `debug-shell` option from `debos` command since this blocks GitHub job from failing.
* Add `scripts/build-supported-configuration.sh` to reduce the number of options required to build an image.
> IMO this should be the default way to run the tool. Many options can be implied from other settings. For example one product means one specific SoC which also means one CPU architecture and boot partition type (usually).
* Update README.md.
* Also change image compress algorithm to `xz` to better match 3rd part distros. This simplifies the installation instruction.

Tested with a few runs.

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Gonna incorporate some changes from [Manjaro ARM](https://github.com/manjaro-arm/radxa-zero-images/blob/master/.github/workflows/image_build_all.yaml). Switch to draft for now.

**Comment by RadxaYuntian** [comment]
Let me know how you think about this. Probably need to do a squash merge since I had too many individual commits for testing.

**Comment by StephenInVamrs** [comment]
Thanks for your support.
 
1.With your all PR commits, I try to build one ROCK 3A ubuntu image. But I get this error log.
  
``` 
2021/12/19 09:50:38     Command: 
2021/12/19 09:50:38     Label: 
Core dump limits :
	soft - NONE
	hard - NONE
Checking that ptrace can change system call numbers...OK
Checking syscall emulation patch for ptrace...OK
Checking advanced syscall emulation patch for ptrace...OK
Checking environment variables for a tempdir...none found
Checking if /dev/shm is on tmpfs...OK
Checking PROT_EXEC mmap in /dev/shm...Operation not permitted
/dev/shm must be not mounted noexec
error starting uml backend: <nil>
====debos rock-3a-ubuntu-focal-server-arm64-gpt end====
TOP DIR = /build/stephen/debos-radxa
```

This error disappears when using debian:testing specified by Dockerfile.
 
2.This PR is for Github CI. build.yml doesn't call dev-shell/Dockerfile. Please do not modify them here.

3.This repository is for both github build and local PC build. dev-shell and Dockerfile are used for local PC build to install specified packages by default.

**Comment by RadxaYuntian** [comment]
For the first issue are you running in a virtual machine? On normal machine debos will first use `/dev/kvm` as backend, which should be available on most modern machines now. In virtual machine you need to either enable nested virtualization to expose `/dev/kvm` , or specify `-tmpfs /dev/shm:rw,nosuid,nodev,exec,size=4g` for your `docker run` to mount `/dev/shm` as `exec`. The reason your Dockerfile worked is because you were running privileged container, which is generally a bad idea.

build.yml doesn't use the old Dockerfile because that is another piece of code to maintain. By using the same docker image provided by the upstream we reduce our burden on maintenance while also ensure that local build will work the same as the GitHub workflow.

I can add an option to mount `/dev/shm` as `exec` but the capability to build locally was never removed.

**Comment by RadxaYuntian** [comment]
This commit should fix your issue. I'm also setting up a vm for testing as well but it gonna take a while.

**Comment by RadxaYuntian** [comment]
Close this PR to break it down.

**Pull request closed without merging**
